name: Hello World

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout our repository
      uses: actions/checkout@v4

    - name: Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          pwd
          ls
          cd exam-4
          sudo docker compose down
          sudo docker compose up -d

          sudo docker compose down
          sudo docker compose up -d

          cd api-gateway
          sudo docker compose down
          sudo docker compose up -d

          cd ..
          cd game-service
          sudo docker compose down
          sudo docker compose up -d


    # - name: install dependencies
    #   run: go mod tidy

    # - name: Build
    #   run: go build -v ./...

    # - name: Test
    #   run: go test -v ./...
